Models/Chart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SSY_Project.Models
{
    public class Chart
    {
        public int Rating { get; set; }
        public string ProductName { get; set; }
    }
}

Controllers/ChartController.cs
using SSY_Project.Models;
using SSY_Project.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSY_Project.Controllers
{
    public class ChartController : Controller
    {
        DatabaseEntities db = new DatabaseEntities();

        // GET: Graph
        public ActionResult Index()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            return View();
        }

        public ActionResult VisualizeResult()
        {
            return Json(categorylist(), JsonRequestBehavior.AllowGet);
        }



        public List<Chart> categorylist()
        {
            List<Chart> c = new List<Chart>();
            c.Add(new Chart()
            {
                CategoryName = "Teknoloji",
                BlogCount = 14
            });
            c.Add(new Chart()
            {
                CategoryName = "Spor",
                BlogCount = 10
            });
            c.Add(new Chart()
            {
                CategoryName = "Kitap",
                BlogCount = 16
            });
            return c;
        }
        //Dinamik Grafik

        public List<Class2> EcsCari()
        {
            List<Class2> cs2 = new List<Class2>();
            using (var c = new DatabaseEntities())
            {

                cs2 = c.Data_ECSCari.Select(x => new Class2
                {
                    BlogName = x.FIRMAADI,
                    Rating = (decimal)x.TUTAR
                }).ToList();
            }
            return cs2;
        }
        public ActionResult VisualizeResult2()
        {
            return Json(EcsCari(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Chart1()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            return View();
        }
        public List<Class2> EcsUrun()
        {
            List<Class2> cs2 = new List<Class2>();
            using (var c = new DatabaseEntities())
            {

                cs2 = c.Data_ECSUrunler.Select(x => new Class2
                {
                    BlogName = x.MALINCINSI,
                    Rating = (decimal)x.CIKAN
                }).ToList();
            }
            return cs2;
        }
        public ActionResult VisualizeResult3()
        {
            return Json(EcsUrun(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Chart2()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            return View();
        }
        public List<Class2> EcsTutar()
        {
            List<Class2> cs2 = new List<Class2>();
            using (var c = new DatabaseEntities())
            {

                cs2 = c.Data_ECSTutar.Select(x => new Class2
                {
                    BlogName = x.MALINCINSI,
                    Rating = (decimal)x.TUTAR
                }).ToList();
            }
            return cs2;
        }
        public ActionResult VisualizeResult4()
        {
            return Json(EcsTutar(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Chart3()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            return View();
        }
        public ActionResult Chart4()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            return View();
        }
    }
}

Controllers/DashboardController.cs
using PagedList;
using SSY_Project.Models;
using SSY_Project.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSY_Project.Controllers
{
    public class DashboardController : Controller
    {
        DatabaseEntities db = new DatabaseEntities();
        // GET: Dashboard
        public ActionResult Index()
        {
            ViewBag.firma = db.Data_Firma.Select(y => y.FIRMAADI).FirstOrDefault();
            ViewBag.logo = db.Data_Firma.Select(x => x.LOGO).FirstOrDefault();
            ViewBag.order = db.Data_GecSipList.Count().ToString();
            ViewBag.product = db.Data_StokList.Count().ToString();
            ViewBag.personal = db.Data_Users.Count().ToString();
            ViewBag.customer = db.Data_CariList.Count().ToString();
            return View();
        }
        public PartialViewResult Weather()
        {

            return PartialView();
        }
        public PartialViewResult Economy()
        {

            return PartialView();
        }
        public PartialViewResult Statistic()
        {

            return PartialView();
        }
        public PartialViewResult EcsUrunler(int sayfa = 1)
        {
            var list = db.Data_ECSUrunler.ToList().ToPagedList(sayfa, 5);
            return PartialView(list);
        }
        public PartialViewResult EcsCari(int sayfa=1)
        {
            var list = db.Data_ECSCari.ToList().ToPagedList(sayfa,5);
            return PartialView(list);
        }
        public PartialViewResult EcsTutar(int sayfa = 1)
        {
            var list = db.Data_ECSTutar.ToList().ToPagedList(sayfa, 5);
            return PartialView(list);
        }

    }
}

Views/Dashboard/Chart.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Google Grafikler</title>
    <style>
        .sedat {
            background-color: yellow;
        }
    </style>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.BlogCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                responsive: true,
                title: "Kategori Blog Statik Pie Grafik",
                //width: 319,
                //height: 200,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('chart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Bar Grafik</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body container float-left">
            @*<div id="Piechart_div" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></div>*@
            <div class="float-left sedat" style="max-height:75%; min-height:25%; max-width:75%;min-width:25%; " id="chart_div"></div>


        </div>
        <!-- /.card-body -->
    </div>
    @*<div id="Piechart_div"></div>*@
</body>
</html>

Views/Dashboard/Economy.cshtml
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
  {
  "symbols": [
    {
      "proName": "BITSTAMP:BTCUSD",
      "title": "Bitcoin"
    },
    {
      "proName": "BITSTAMP:ETHUSD",
      "title": "Ethereum"
    },
    {
      "description": "Dolar",
      "proName": "FX:USDTRY"
    },
    {
      "description": "Euro",
      "proName": "OANDA:EURTRY"
    }
  ],
  "showSymbolLogo": true,
  "colorTheme": "light",
  "isTransparent": false,
  "displayMode": "adaptive",
  "locale": "tr"
}
    </script>
</div>

Views/Dashboard/EcsCari.cshtml
@using SSY_Project.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Data_ECSCari>

@{int sira = 1; }
<div class="card">
    <div class="card-header">
        <div class="float-left">
            <h3 class="card-title">EcsCari</h3>
        </div>
        <div class="float-right">
            <a href="/Chart/Chart2" class="btn btn-danger btn-sm"><i class="fas fa-chart-area"></i> Grafik</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>FİRMA ADI</th>
                    <th>TUTAR BAR</th>
                    <th style="width: 40px">TUTAR</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@sira</td>
                        <td>@item.FIRMAADI</td>
                        <td>

                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: @Convert.ToInt32(item.TUTAR/1000)%"></div>
                            </div>


                        </td>
                        <td><span class="badge bg-danger">@item.TUTAR ₺</span></td>
                    </tr>
                    sira++;
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        <div class="float-right">
            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
               {
                LiElementClasses = new List<string>
                {"page-link"}
                })
        </div>

    </div>
</div>

Views/Dashboard/EcsTutar.cshtml
@using SSY_Project.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Data_ECSTutar>
@{int sira = 1; }
<div class="card">
    <div class="card-header">
        <div class="float-left">
            <h3 class="card-title">EcsTutar</h3>
        </div>
        <div class="float-right">
            <a href="/Chart/Chart3" class="btn btn-danger btn-sm"><i class="fas fa-chart-area"></i> Grafik</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>MALIN CİNSİ</th>
                    <th>TUTAR BAR</th>
                    <th style="width: 40px">TUTAR</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@sira</td>
                        <td>@item.MALINCINSI</td>
                        <td>

                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: @Convert.ToInt32(item.TUTAR/1000)%"></div>
                            </div>


                        </td>
                        <td><span class="badge bg-danger">@item.TUTAR ₺</span></td>
                    </tr>
                    sira++;
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        <div class="float-right">
            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
               {
                LiElementClasses = new List<string>
                {"page-link"}
                })
        </div>
    </div>
</div>

Views/Dashboard/EcsUrunler.cshtml
@using SSY_Project.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Data_ECSUrunler>
@{int sira = 1; }
<div class="card">
    <div class="card-header">
        <div class="float-left">
            <h3 class="card-title">EcsÜrünler</h3>
        </div>
        <div class="float-right">
            <a href="/Chart/Chart1" class="btn btn-danger btn-sm"><i class="fas fa-chart-area"></i> Grafik</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>MALIN CİNSİ</th>
                    <th>ÇIKAN BAR</th>
                    <th style="width: 40px">ÇIKAN</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@sira</td>
                        <td>@item.MALINCINSI</td>
                        <td>

                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: @Convert.ToInt32(item.CIKAN/1000)%"></div>
                            </div>


                        </td>
                        <td><span class="badge bg-danger">@item.CIKAN ₺</span></td>
                    </tr>
                    sira++;
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        <div class="float-right">
            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
               {
                LiElementClasses = new List<string>
                {"page-link"}
                })
        </div>
    </div>
</div>

Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

@Html.Partial("Weather", "Dashboard")
<br />

@Html.Partial("Economy", "Dashboard")

@Html.Partial("Statistic", "Dasboard")


<div class="row">
    <!-- Left col -->
    <section class="col-lg-6 float-left connectedSortable">
        @Html.Action("EcsUrunler", "Dashboard")
    </section>
    <section class="col-lg-6 float-right connectedSortable">
        @Html.Action("EcsCari", "Dashboard")
    </section>
</div>
<div class="row">
    <!-- Left col -->
    <section class="col-lg-12  connectedSortable">
        @Html.Action("EcsTutar", "Dashboard")
    </section>
    @*<section class="col-lg-6 float-right connectedSortable">
        @Html.Action("EcsCari", "Dashboard")
    </section>*@
</div>

Views/Dashboard/Statistic.cshtml
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>@ViewBag.order</h3>

                <p>Siparişler</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="/Order/Index" class="small-box-footer">Daha Fazlası <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@ViewBag.product</h3>

                <p>Ürün Sayısı</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="/Stok/Index" class="small-box-footer">Daha Fazlası <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6 text-white">
        <!-- small box -->
        <div class="small-box bg-warning ">
            <div class="inner">
                <h3>@ViewBag.personal</h3>

                <p>Personel Sayısı</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>

            <a style="text-align:center" href="#" class="text-white small-box-footer"> Daha Fazlası <i class="fas fa-arrow-circle-right"></i></a>

        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>@ViewBag.customer</h3>

                <p>Müşteri Sayısı</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-stalker"></i>
            </div>
            <a href="/Customer/Index" class="small-box-footer">Daha Fazlası <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>

Views/Dashboard/Weather.cshtml
<a class="weatherwidget-io" href="https://forecast7.com/tr/41d0128d98/istanbul/" data-label_1="İSTANBUL" data-label_2="HAVA DURUMU" data-theme="marine">İSTANBUL HAVA DURUMU</a>
<script>
    !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = 'https://weatherwidget.io/js/widget.min.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'weatherwidget-io-js');
</script>